networks:
  pfg-network:
    name: pfg-network

volumes:
  pfg-mongo-data:

services:
  pfg-backend:
    hostname: pfg-backend
    image: pfg-backend:latest
    container_name: pfg-backend
    depends_on:
      - pfg-mongodb
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: npm run start:dev
    env_file: ./.env
    environment:
      - NODE_ENV=production
    networks:
      - pfg-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    restart: unless-stopped

  pfg-mongodb:
    image: mongo:7.0
    container_name: pfg-mongodb
    volumes:
      - pfg-mongo-data:/data/db
    networks:
      - pfg-network
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    restart: unless-stopped
